[build]
  command = "npm install && npm run build"
  publish = "build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "20.18.1"
  NPM_VERSION = "10.8.2"